/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_transactions_get"];
        put?: never;
        /** Create Transaction */
        post: operations["create_transaction_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Transaction */
        delete: operations["delete_transaction_transactions__transaction_id__delete"];
        options?: never;
        head?: never;
        /** Update Transaction */
        patch: operations["update_transaction_transactions__transaction_id__patch"];
        trace?: never;
    };
    "/commissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Commissions */
        get: operations["list_commissions_commissions_get"];
        put?: never;
        /** Create Commission */
        post: operations["create_commission_commissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/commissions/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Commissions Summary */
        get: operations["commissions_summary_commissions_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/commissions/{commission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Commission */
        delete: operations["delete_commission_commissions__commission_id__delete"];
        options?: never;
        head?: never;
        /** Update Commission */
        patch: operations["update_commission_commissions__commission_id__patch"];
        trace?: never;
    };
    "/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Summary */
        get: operations["dashboard_summary_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dashboard Insights */
        post: operations["dashboard_insights_dashboard_insights_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cashflow/radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cashflow Radar Endpoint */
        get: operations["cashflow_radar_endpoint_cashflow_radar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cashflow/radar/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cashflow Insights */
        post: operations["cashflow_insights_cashflow_radar_insights_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Stream */
        post: operations["chat_stream_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CashflowInsightsResponse */
        CashflowInsightsResponse: {
            radar: components["schemas"]["CashflowRadarRead"];
            /** Narrative */
            narrative: string;
        };
        /** CashflowRadarRead */
        CashflowRadarRead: {
            /** Balance */
            balance: number;
            /** Burn Per Day */
            burn_per_day: number;
            /** Burn Next 30D */
            burn_next_30d: number;
            /** Committed Next 30D */
            committed_next_30d: number;
            /** Projected Balance 30D */
            projected_balance_30d: number;
            /** Coverage Pct */
            coverage_pct: number | null;
            /**
             * Level
             * @enum {string}
             */
            level: "healthy" | "moderate" | "low" | "unknown";
            /** As Of */
            as_of: string;
            /** Projection */
            projection: components["schemas"]["RadarPoint"][];
            /** Runway Days */
            runway_days: number | null;
            /** Projected Zero Date */
            projected_zero_date: string | null;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "supplies" | "platform_fees" | "subscriptions" | "equipment" | "other_expense";
        /** ChatRequest */
        ChatRequest: {
            /** Question */
            question: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
        };
        /**
         * CommissionCreate
         * @description API boundary: accepts dollars, exposes integer cents to the domain.
         */
        CommissionCreate: {
            /** Client */
            client: string;
            /** Piece */
            piece: string;
            /**
             * Hours Spent
             * @default 0
             */
            hours_spent: number;
            /** Amount */
            amount?: number | null;
            /** Expected Date */
            expected_date?: string | null;
            /** @default in_progress */
            status: components["schemas"]["CommissionStatus"];
            /** Transaction Id */
            transaction_id?: number | null;
        };
        /** CommissionRead */
        CommissionRead: {
            /** Id */
            id: number;
            /** Client */
            client: string;
            /** Piece */
            piece: string;
            /** Hours Spent */
            hours_spent: number;
            /** Amount */
            amount: number | null;
            /** Expected Date */
            expected_date: string | null;
            /** Status */
            status: string;
            /** Transaction Id */
            transaction_id: number | null;
            /** Income Autologged */
            income_autologged: boolean;
            /** Effective Rate */
            effective_rate: number | null;
        };
        /**
         * CommissionStatus
         * @enum {string}
         */
        CommissionStatus: "agreed" | "in_progress" | "completed" | "cancelled";
        /** CommissionSummary */
        CommissionSummary: {
            /** Expected Income */
            expected_income: number;
            /** Earned Income */
            earned_income: number;
            /** Lost Income */
            lost_income: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Active Count */
            active_count: number;
        };
        /**
         * CommissionUpdate
         * @description Terms (price, hours, expected date) lock when the commission is logged.
         *
         *     Only progress — the status — can be updated afterwards.
         */
        CommissionUpdate: {
            status: components["schemas"]["CommissionStatus"];
        };
        /** DashboardSummary */
        DashboardSummary: {
            /** Balance */
            balance: number;
            /** Per Source Net */
            per_source_net: {
                [key: string]: number;
            };
            /** Monthly Trend */
            monthly_trend: components["schemas"]["TrendPoint"][];
            /** Top Merchants */
            top_merchants: components["schemas"]["MerchantTotal"][];
            /** Total Fees */
            total_fees: number;
            /** Hourly Rate */
            hourly_rate: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InsightsResponse */
        InsightsResponse: {
            /** Insights */
            insights: string;
        };
        /** MerchantTotal */
        MerchantTotal: {
            /** Merchant */
            merchant: string;
            /** Total */
            total: number;
        };
        /** RadarPoint */
        RadarPoint: {
            /** Day */
            day: number;
            /** Date */
            date: string;
            /** Balance */
            balance: number;
        };
        /**
         * Source
         * @enum {string}
         */
        Source: "commission" | "etsy" | "patreon" | "other_income";
        /**
         * TransactionCreate
         * @description API boundary: accepts dollars, exposes integer cents to the domain.
         */
        TransactionCreate: {
            /**
             * Type
             * @enum {string}
             */
            type: "income" | "expense";
            /** Amount */
            amount: number;
            /** Description */
            description: string;
            /**
             * Date
             * Format: date
             */
            date?: string;
            /** Fee Amount */
            fee_amount?: number | null;
            source?: components["schemas"]["Source"] | null;
            category?: components["schemas"]["Category"] | null;
            /** Merchant */
            merchant?: string | null;
        };
        /** TransactionRead */
        TransactionRead: {
            /** Id */
            id: number;
            /**
             * Type
             * @enum {string}
             */
            type: "income" | "expense";
            /** Amount */
            amount: number;
            /** Net Amount */
            net_amount: number | null;
            /** Description */
            description: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Fee Amount */
            fee_amount: number | null;
            source: components["schemas"]["Source"] | null;
            category: components["schemas"]["Category"] | null;
            /** Merchant */
            merchant: string | null;
            /** Auto Categorized */
            auto_categorized: boolean;
        };
        /** TransactionUpdate */
        TransactionUpdate: {
            /** Amount */
            amount?: number | null;
            /** Description */
            description?: string | null;
            /** Date */
            date?: string | null;
            /** Fee Amount */
            fee_amount?: number | null;
            source?: components["schemas"]["Source"] | null;
            category?: components["schemas"]["Category"] | null;
            /** Merchant */
            merchant?: string | null;
        };
        /** TrendPoint */
        TrendPoint: {
            /** Month */
            month: string;
            /** Income */
            income: number;
            /** Expense */
            expense: number;
            /** Net */
            net: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_transactions_transactions_get: {
        parameters: {
            query?: {
                source?: string | null;
                category?: string | null;
                type?: string | null;
                from_date?: string | null;
                to_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transaction_transactions__transaction_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_transaction_transactions__transaction_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_commissions_commissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommissionRead"][];
                };
            };
        };
    };
    create_commission_commissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommissionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommissionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commissions_summary_commissions_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommissionSummary"];
                };
            };
        };
    };
    delete_commission_commissions__commission_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commission_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_commission_commissions__commission_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commission_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommissionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommissionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_summary_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    dashboard_insights_dashboard_insights_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsResponse"];
                };
            };
        };
    };
    cashflow_radar_endpoint_cashflow_radar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashflowRadarRead"];
                };
            };
        };
    };
    cashflow_insights_cashflow_radar_insights_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashflowInsightsResponse"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
